3 lesson homework done
bizibi/React-thinknetica- pull request #3
Opened 2020-09-07 20:30 UTC by bizibi

Домашнее задание к третьему уроку.

2020-09-08 11:12 UTC, index01d requested changes

2020-09-08 11:12 UTC, index01d commented on src/context/AuthorContext.js
> +import AuthorCard from "../components/author/AuthorCard";
? Похоже не используется

2020-09-08 11:12 UTC, index01d commented on src/context/AuthorContext.js
> +const AuthorContext = createContext({});
Не нашел реализацию AuthorContext.Provider

2020-09-08 18:23 UTC, bizibi commented on src/context/AuthorContext.js
> +import AuthorCard from "../components/author/AuthorCard";
исправил

2020-09-08 18:29 UTC, bizibi commented on src/context/AuthorContext.js
> +const AuthorContext = createContext({});
Тут: src/components/user/UserInfo.js

2020-09-09 20:54 UTC, index01d approved these changes

2020-09-13 14:11 UTC, merged